language: rust
sudo: false
matrix:
  include:
    - rust: 1.14.0
    - rust: stable
    - rust: beta
    - rust: nightly
script:
  - |
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --features "$FEATURES" &&
      ([ "$BENCH" != 1 ] || cargo bench --verbose --features "$FEATURES") &&
      cargo doc --verbose --features "$FEATURES"
